### PR TITLE
Fix unparsable JSON

### LINKED ISSUE #92: Atom Incredibly slowed down atom if the package.json is unparsable when linter-xo is enabled
[Issuehunt badges](https://issuehunt.io/r/xojs/atom-linter-xo/issues/92)

## Problem
If the `package.json` contains some syntax errors atom-lint task never ends and after a while it makes atom unresponsive.
The only solution to allow the task to complete again after fixing the syntax error is to restart atom.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/xojs/atom-linter-xo/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by BarryThePenguin**
When `package.json` contains a syntax error, `findPackage()` is called repetitively, as `base` is never `null`.

This uses https://github.com/sindresorhus/pkg-up, which does return `null` if a `package.json` file isn't found

Fixes #92

### CODE REVIEW

File: lib/get-package-path.js [hunk 1]
```diff
@@ -1,16 +1,17 @@
...
 const DEFAULT_PACKAGE = {xo: false};
 
 // (base: string) => pkgPath: Promise<string>
 async function findPackage(base) {
-	const pkgPath = path.join(base, 'package.json');
+	const pkgPath = await pkgUp({cwd: base});
 	const pkg = await loadPkg(pkgPath);
 
-	if (pkg.xo === false && base !== null) {
-		return findPackage(path.join(base, '..'));
```
Comment (BarryThePenguin) [inline lib/get-package-path.js:13]: `path.join(base, '..')` was never `null`, so if a `package.json` wasn't found, `findPackage('/')` would be called repeatedly

File: lib/get-package-path.js [hunk 2]
```diff
@@ -1,16 +1,17 @@
...
+	if (pkg.xo === false && pkgPath !== null) {
+		const newBase = path.resolve(path.dirname(pkgPath), '..');
+		return getPackagePath(newBase);
```
Comment (BarryThePenguin) [inline lib/get-package-path.js:14]: Calculates a new `base` path from the directory above any `package.json` file found.

This way, `pkg-up` will handle _most_ of the directory traversal. If it finds a `package.json` file with `pkg.xo === false` it continues traversing up.

When `/` is reached, it returns `null`.

File: mocks/unparsable/package.json [hunk 3]
```diff
@@ -0,0 +1,6 @@
+{
+  "name": "unparsable",,,,
+  "devDependencies": {
+    "xo": "*"
+  }
+}
```
Comment (BarryThePenguin) [inline mocks/unparsable/package.json:6]: It doesn't look like it's feasible to have a test for this situation.. Based on CI

```
> xo --ignore='mocks/**/*'
JSONError: JSON Error in /home/travis/build/xojs/atom-linter-xo/mocks/unparsable/package.json: 
  1 | {
> 2 |   "name": "unparsable",,,,
    |                        ^
  3 |   "devDependencies": {
  4 |     "xo": "*"
  5 |   }
Unexpected token "," (0x2C) in JSON at position 25 while parsing near "...name\": \"unparsable\",,,,\n  \"devDependenci..." 
  1 | {
> 2 |   "name": "unparsable",,,,
    |                        ^
  3 |   "devDependencies": {
  4 |     "xo": "*"
  5 |   }
    at module.exports (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/node_modules/parse-json/index.js:29:21)
    at Object.loadJson (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/loaders.js:28:20)
    at Explorer.loadPackageProp (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/ExplorerBase.js:82:44)
    at Explorer.loadFileContent (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/Explorer.js:89:36)
    at runLoad (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/Explorer.js:103:33)
    at async cacheWrapper (/home/travis/build/xojs/atom-linter-xo/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async Promise.all (index 4)
    at async Object.lintFiles (/home/travis/build/xojs/atom-linter-xo/node_modules/xo/index.js:100:23)
    at async /home/travis/build/xojs/atom-linter-xo/node_modules/xo/cli-main.js:185:18
```
