### PR TITLE
Disable rules when fixing on save

### LINKED ISSUE #89: Allow to disable some rules when fixing on save
The Fix on Save feature is really useful, but with some rules it can sometime get in the way.
For example with the [capitalized-comments](https://eslint.org/docs/rules/capitalized-comments).

When developing is sometimes to comment out a few lines of code to test something and revert the commenting to re-eanable the code.

With the `capitalized-comments` rule, if Fix on Save is enable, commenting a few line of code will capitalize the first letter. When un-commenting the capital letter will stay and has to be manually fixed.

For example, this following code might create a problem and I comment it to test:
```js
// if (condition) {
//   createPossibleProblem();
// }
```
On save `if` becomes `If`:
```js
// If (condition) {
//   createPossibleProblem();
// }
```
When I un-comment the code `If` stay capitalized.

See the same feature on [linter-eslint](https://github.com/AtomLinter/linter-eslint) : AtomLinter/linter-eslint#795

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #89

Add a new config that allows to define rules that will not be automatically fixed when saving.
Set by default with [capitalized-comments](https://eslint.org/docs/rules/capitalized-comments) and [no-only-test](https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-only-test.md).

Errors will still be fixed when running the command `XO:Fix`.

The test currently fails because an issue with [deep-assign](https://github.com/sindresorhus/deep-assign) in XO. When passing the `fix` as a function, `deep-assign` replaces it with `{}`.
Passing the option `{fix: () => {...}}` through `deep-assign` results in `{fix: {}}`.

This is fixed by [4f4de13](https://github.com/sindresorhus/xo/commit/4f4de133b3c015387efcc34ab579d54da9bc7e87), but this commit is not released yet. As soon a new version of XO is released the tests will work.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> This is fixed by 4f4de13, but this commit is not released yet. As soon a new version of XO is released the tests will work.

Can you bump XO here?

**Comment by pvdlg** [comment]
Done !

**Comment by pvdlg** [comment]
It seems there is an issue on the Travis build: `Xlib:  extension "RANDR" missing on display ":99".`

**Comment by Arcanemagus** [comment]
> It seems there is an issue on the Travis build: Xlib: extension "RANDR" missing on display ":99".

This can safely be ignored.

FYI, the officially recommended CI scripts are located in https://github.com/atom/ci, although nobody has bothered to fix it there because it doesn't actually change anything.

If you were curious, to fix this you need to add [`+extension RANDR`](https://github.com/Arcanemagus/atom-docker-ci/blob/master/xvfb_start.sh#L4) to the `Xvfb` arguments.

**Comment by pvdlg** [comment]
Thanks for the info! Really helpful.

So I have to figure out why `apm test` fails on Travis but works locally...

**Comment by Arcanemagus** [comment]
Took a look at the build, generally when `apm test` has _no_ output like that, it means that Atom encountered an error before the specs could start. _Usually_ this is due to encountering syntax it doesn't understand, but it could be anything.

You can probably get this output to show by changing `apm test` to `atom --enable-electron-logging --test spec.js`. (I think that's the right syntax for a single file?)

**Comment by pvdlg** [comment]
Thanks!
For info I tried to use the official script from https://github.com/atom/ci. `apm` works but `atom` doesn't. After installing `~/atom/usr/bin/atom -v` doesn't return anything.

**Comment by pvdlg** [comment]
Using the [official scripts](https://github.com/atom/ci) it seems to work. The test had to be put in the `spec` folder in order to be [ran by the scripts](https://travis-ci.org/xojs/atom-linter-xo/builds/342197372#L1883).

Running the test from an npm script or directly in Travis doesn't work.

**Comment by Arcanemagus** [comment]
Hmmm, sorry, I just looked in detail at what you are doing here. The reason `apm test` failed before is that you _have_ no Jasmine 1.3 specs, the only format that Atom understands by default. Atom does support alternative test runners, but I don't think anyone has written one for `ava` yet.

It seems the current setup works, though it just runs a "spec" of 0 tests within Atom. I'd say just leave it as is though since the script will install Atom for you and should be kept up to date for you with any changes needed.

**Comment by pvdlg** [comment]
Thanks for the help :)
The spec is written with Jasmine: https://github.com/xojs/atom-linter-xo/pull/90/files#diff-e1eba628503a5c40e269db41c03ec220

So I guess that spec should run?

There is some ava test files as well but they just test individual modules and they are run in Travis with `npm test`.

**Comment by pvdlg** [comment]
You're right the tests are not running: https://travis-ci.org/xojs/atom-linter-xo/builds/342197372#L1889

I don't know why. I looked at several of Atom Linter project and they all have their Jasmine specs in a `spec` folder and the CI script run them...

**Comment by Arcanemagus** [comment]
I've always named the file `something-spec.js`, I don't know how it would behave with just `spec.js`. Does it work locally?

**Comment by pvdlg** [comment]
No, but it seems that naming the file `something-spec.js` works.

**Comment by pvdlg** [comment]
It failed :( https://travis-ci.org/xojs/atom-linter-xo/builds/342209740#L1859

Unfortunately I can't run `atom --enable-electron-logging --test spec.js` in the CI because the `atom` bin is not found.

**Comment by Arcanemagus** [comment]
Fascinating, I can't get it to fail locally under any of the environments I have set up. The next step I would take would be to essentially stick the important parts of `build-package.sh` directly in the build script so I could insert the debugging version instead, or alternatively fork that script, insert it, and switch the build here to use the forked version temporarily.

I can work on that tomorrow if you don't figure it out before hand.

**Comment by pvdlg** [comment]
That's a good idea! I'll try that, but it's getting very late for me so it will have to wait until tomorrow as well. Any help is much appreciated!

**Comment by pvdlg** [comment]
`language: generic` in `.travis.yml` seems to fix the Atom spec.
I guess it's only because by default the `generic` image happen to come with a Node version compatible with Atom.
If you run with a Node image that specifies version 8 or 9 then you get:
```
[6797:0216/064237.292221:INFO:CONSOLE(109)] "Error: The module '/home/travis/build/xojs/atom-linter-xo/node_modules/pathwatcher/build/Release/pathwatcher.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

I imagine the day Travis decide to update their default Node version on their `generic` image that will happen as well.

**Comment by Arcanemagus** [comment]
Actually, the issue with `language: node` is that unless you override it Travis automatically "helps" you by [running `npm install`](https://travis-ci.org/xojs/atom-linter-xo/builds/342215499#L514), which happens before the `script` step. In this case that is building the wrong version of the native modules.

If you want to use that image you just need to [skip the `install` step](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step).

**Comment by pvdlg** [comment]
Thanks for the info. So I guess I can use a Node image and if I override the `install` step to run what I have now it should work.

**Comment by Arcanemagus** [comment]
Looks like that did it!

**Comment by pvdlg** [comment]
Yep I noticed as well... It's really weird...

**Comment by pvdlg** [comment]
ah my bad, I renamed the test `spec.js` by mistake

**Comment by pvdlg** [comment]
Seems good now, the test are running now https://travis-ci.org/xojs/atom-linter-xo/builds/342474730#L540

**Comment by Arcanemagus** [comment]
Looks like a `.DS_Store` file snuck in there. 😆

**Comment by pvdlg** [comment]
> Looks like a .DS_Store file snuck in there. 😆

Oops. It's fixed now.

File: lib/fix.js [hunk 1]
```diff
@@ -4,8 +4,9 @@ import lint from './lint';
 // (editor: Object) => function
 export default function fix(editor) {
 	// (text: string) => Promise<void>
-	return text => {
-		return lint(editor)(text, {fix: true})
+	return (text, exclude) => {
+		const fix = exclude ? report => exclude.indexOf(report.ruleId) === -1 : true;
```
Comment (sindresorhus) [inline lib/fix.js]: `indexOf` => `includes`

Comment (pvdlg) [reply lib/fix.js]: Done!

File: .travis.yml [hunk 2]
```diff
@@ -1,12 +1,17 @@
 language: node_js
 node_js:
   - 'node'
-before_script:
-  - bash <(curl -s https://raw.githubusercontent.com/wooorm/atom-travis/master/install.sh)
-  - export DISPLAY=":99"
+install:
+  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
+  - chmod u+x build-package.sh
+  - ./build-package.sh
```
Comment (sindresorhus) [inline .travis.yml]: @wooorm FYI

**Comment by sindresorhus** [comment]
This looks great. Thanks for helping us out @Arcanemagus :)

File: .travis.yml (hunk 2 above)
Comment (wooorm) [reply .travis.yml]: @sindresorhus Hmm? Do we need a change in atom-linter-xo?

Comment (sindresorhus) [reply .travis.yml]: No, I mean, we had to stop using `wooorm/atom-travis` because it was no longer working.

Comment (wooorm) [reply .travis.yml]: Oh sorry, I missed the context. That’s a pity! Thanks for letting me know. I’ll investigate it when I need to use it again as well 👍
